version: 2

jobs:
  tests:
    docker:
      - image: python:3.6-alpine3.9
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv

            python3.6 -mvirtualenv --no-site-packages --no-download .

            source bin/activate

            pip install -r requirements.txt

            mkdocs build --clean --site-dir _build/html --config-file ./mkdocs.yml


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
