site_name: Web3 Hub
site_author: 'Web3 Foundation'

# theme:
#  name: 'material'
#  palette:
#    primary: 'deep orange'
#    accent: 'deep orange'
#  logo: 'images/logo.svg'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/w3f'
    - type: 'twitter'
      link: 'https://twitter.com/web3foundation'
    - type: 'medium'
      link: 'https://medium.com/web3foundation'

# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#   - mathjax-config.js

# markdown_extensions:
#    - mdx_math
